<?php

namespace Hotel\Bundle\RoomsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * camereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class camereRepository extends EntityRepository
{
}
